### PR TITLE
src and other things are added

### PR DESCRIPTION
**Pull request by Monty-00**
@Shubhanshu07

### CODE REVIEW

**Comment by Monty-00** [comment]
sir now there are screen shots and some actual images only.

**Comment by Monty-00** [comment]
@Shubhanshu07

**Comment by agshubhs** [comment]
@monty add that screenshot on Readme also
If it creates any problem then change the name of the image.

**Comment by Monty-00** [comment]
I added it in README.md file @Shubhanshu07

**Comment by agshubhs** [comment]
@Monty-00 PR looks good to me. Nice Work
Hence merging it

**Pull request merged**
